test22

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,6 +17,11 @@ jobs:
     
     - name: Run Test1
       run: |
-        node dist/Test1.js
-      
+        output=$(node dist/Test1.js)
+        exit_code=$output
+
+        if [ $exit_code -ne 0 ]; then
+          echo "Error $exit_code"
+          exit 1
+        fi 
 
